[package]
name = "aoc-01"
version = "0.1.0"
authors = ["Hannes Sn√∂gren <hannes.snogren@configura.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
